NTOT:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.ConsistencyCheck
    parameter_sets:
       - [ 'NTRZ', 'AMON' ]
       - [ 'NTRA', 'NTRI', 'AMON' ]
    sigma: 0  # NTOT includes dissolved, particulate organic nitrogen, strict limit no uncertainty
    upper_limit: 999
PTOT:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.ConsistencyCheck
    parameter_sets:
        - ['PHOS']
    sigma: 0  # PTOT includes dissolved, particulate organic phosphorous, strict limit no uncertainty
    upper_limit: 999
TOC:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.ConsistencyCheck
    parameter_sets:
      - ['DOC', 'POC']
    sigma: 70  # std. uncertainty, from U2=30% for all params, using median values from SHARK (2026-01-13)
    upper_limit: 999  #
DOXY_CTD:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.ConsistencyCheck
    parameter_sets:
      - ['DOXY_BTL']
    sigma: 0.3  # std. uncertainty, SMHI from U2=6% for BTL (applying the same for CTD), using median values from SHARK (2026-01-13)
    upper_limit: None
SALT_BTL:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.ConsistencyCheck
    parameter_sets:
      - ['SALT_CTD']
    sigma: 0.02  # std. uncertainty, SMHI U2=0.02 for BTL and U2=0.04 for CTD
    upper_limit: None
