ALKY:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 5
AMON:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 1500
CNDC_CTD:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 5000
CPHL:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 150
DEPH:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 5000
DOXY_BTL:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 12
DOXY_CTD:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 12
H2S:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 500
HUMUS:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 200
NTOT:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 700
NTRA:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 300
NTRI:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 50
NTRZ:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 300
PHOS:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 100
PH_TOT:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 5
    max_range_value: 9
PH:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 5
    max_range_value: 9
PH_LAB:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 5
    max_range_value: 9
PRES_CTD:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 5000
PTOT:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 100
SIO3-SI:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 400

SALT_BTL:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 36
SALT_CTD:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 36
TEMP_BTL:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: -2
    max_range_value: 35
TEMP_CTD:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: -2
    max_range_value: 35
TOC:
  global: !!python/object:ocean_data_qc.fyskem.qc_checks.RangeCheck
    min_range_value: 0
    max_range_value: 10
