
PHOS:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/PHOS.txt"
NTRZ:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/NTRZ.txt"
din:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/din.txt"
AMON:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/AMON.txt"
doxy:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/doxy.txt"
DOXY_BTL:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/DOXY_BTL.txt"
SALT_BTL:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/SALT_BTL.txt"
NTOT:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/NTOT.txt"
PTOT:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/PTOT.txt"
CPHL:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/CPHL.txt"
TEMP_BTL:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/TEMP_BTL.txt"
salt:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/salt.txt"
temp:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/temp.txt"
oxygen_saturation:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/oxygen_saturation.txt"
SECCHI:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/SECCHI.txt"
NTRI:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/NTRI.txt"
TEMP_CTD:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/TEMP_CTD.txt"
SIO3-SI:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/SIO3-SI.txt"
SALT_CTD:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/SALT_CTD.txt"
PH:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/PH.txt"
H2S:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/H2S.txt"
DOXY_CTD:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/DOXY_CTD.txt"
ALKY:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/ALKY.txt"
NTRA:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/NTRA.txt"
HUMUS:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/HUMUS.txt"
PH_LAB:
    !!python/object:ocean_data_qc.fyskem.qc_checks.StatisticCheck
    filepath: "configs/statistic_check_data/PH_LAB.txt"